services:
  postgres:
    image: postgres:16-alpine
    container_name: pokedex-postgres
    environment:
      POSTGRES_DB: app_pokedex
      POSTGRES_USER: user_pokedex
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_pokedex -d app_pokedex"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: pokedex-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_pokedex
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: app_pokedex
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ping:1})' --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
