spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_pokedex
    username: user_pokedex
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    mongodb:
      username: admin_pokedex
      password: '123456'
      host: localhost
      port: 27017
      database: app_pokedex
      authentication-database: app_pokedex

app:
  seguranca:
    token-admin: token-dev-alterar-em-producao
